import LogoutButton from '@/components/LogOutButton';
import { AuthProvider } from '../app/lib/auth/AuthContext';
import { ErrorBoundary } from '../components/ErrorBoundary';
import SupabaseProviders from './SupabaseProviders';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ErrorBoundary>
          <SupabaseProviders>
            <AuthProvider>
              {children}
            </AuthProvider>
          </SupabaseProviders>
        </ErrorBoundary>
      </body>
    </html>
  )
}
